### ISSUE TITLE
Plan v5 Release

### ISSUE THREAD

**Issue by bertdeblock** [ember-cli/ember-cli#10163]
### Clean up Deprecations

- [x] https://github.com/ember-cli/ember-cli/pull/10175
- [x] https://github.com/ember-cli/ember-cli/pull/10184
- [x] https://github.com/ember-cli/ember-cli/pull/10184
- [x] https://github.com/ember-cli/ember-cli/pull/10221
- [x] https://github.com/ember-cli/ember-cli/pull/10177
- [x] https://github.com/ember-cli/ember-cli/pull/10183
- [x] https://github.com/ember-cli/ember-cli/pull/10182
- [x] https://github.com/ember-cli/ember-cli/pull/10176

### Merge Open Pull Requests

- [x] https://github.com/ember-cli/ember-cli/pull/10019
- [x] https://github.com/ember-cli/ember-cli/pull/10106

### Additional Work

- [x] https://github.com/ember-cli/ember-cli/pull/10217
- [x] #10178 
- [x] #10186
- [x] Stop using `ember-cli-babel`'s [`configKey`](https://github.com/babel/ember-cli-babel/blob/master/index.js#L26) property
  - Not necessary anymore to use this property, we can just hardcode `'ember-cli-babel'` where needed (more info: https://github.com/babel/ember-cli-babel/pull/105)
- [x] Drop support for `ember-cli-babel` v6 and lower
  - We have a few checks for `ember-cli-babel` v6 and lower, I think it's safe to remove these
- [x] Drop support for the `EMBER_CLI_IGNORE_ADDON_NAME_MISMATCH` env var
  - This env var suppresses [this error](https://github.com/ember-cli/ember-cli/blob/0f924a2d3342db30b6eb30bcce4a1df8bd120272/lib/models/addon.js#L417-L422), the env var was supposed to be removed in `ember-cli` v3.10, making sure the error is always thrown - https://github.com/ember-cli/ember-cli/pull/10225
- [x] Drop support for finding addons by their `index.js` name, at the moment, we just [warn](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/find-addon-by-name.js#L24-L28) - https://github.com/ember-cli/ember-cli/pull/10223
  - We already removed support for finding scoped addons using their unscoped name [here](https://github.com/ember-cli/ember-cli/pull/9908)
- [x] Drop support for the following vendor files:
  - [x] [`ember-cli-shims`](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L469) - not necessary anymore
  - [x] [`ember.paths.shims`](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L480) - does not exist anymore
  - [x] All vendor files coming in via Bower, as Bower support will be dropped
    - [x] https://github.com/ember-cli/ember-cli/pull/10217
    - [x] https://github.com/ember-cli/ember-cli/pull/10218
  - [x] [`jquery.js`](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L578) - `ember-source` does not provide `ember.paths.jquery` anymore and Bower support will be dropped - https://github.com/ember-cli/ember-cli/pull/10195
- [x] https://github.com/ember-cli/ember-cli/pull/10229
- [x] Drop support for NPM v5.7.1 and lower [here](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js#L215-L228) - https://github.com/ember-cli/ember-cli/pull/10219
- [x] Remove `ember-cli-babel` fallback - Require v1 addons to always specify `ember-cli-babel` in their `dependencies` - https://github.com/ember-cli/ember-cli/pull/10232
- [x] Always throw on invalid addon paths (remove `EMBER_CLI_ERROR_ON_INVALID_ADDON` env flag) - https://github.com/ember-cli/ember-cli/pull/10185
- [x] Remove default `minifyJS` options - https://github.com/ember-cli/ember-cli/pull/10197

### Additional Checks

- [x] Make sure all Bower related code is cleaned up (including dependencies) - https://github.com/ember-cli/ember-cli/pull/10226
- [x] Make sure all JSHint related code is cleaned up (test files as well)
- [x] Make sure all until `5.0` deprecations have deprecation guides - https://github.com/ember-learn/deprecation-app/pull/1314

### Documentation

TODO.

**Comment by Pheromon** [comment]
Will you raise minimum required node version to 18, since it's a LTS release?

**Comment by bertdeblock** [comment]
v5 will still support Node v16, also v5 will not be an LTS if I'm not mistaken.

**Comment by bertdeblock** [comment]
> since it's a LTS release?

Or do you mean that Node v18 is an LTS release?

**Comment by Pheromon** [comment]
yes I was talking about node LTS, and if ember-cli v5 is not LTS then you are right: there is not such need to raise the minimum supported versions
