### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by abuiles** [ember-cli/ember-cli#2120]
Based on https://twitter.com/stefanpenner/status/514247780593070080, we should have this issue so it's easier to know what needs to be improved.

It will also help people who want to contribute somehow but don't know where to start.

- [x]  Improve documentation for generators/blueprints (e.g. mention --help, available options for some of then, etc)
- [x]  Add addons docs  - WIP [#1862]
- [x]  Explain current workaround for source maps (people ask about this quite often)
- [x]  Shall we try to explain ES6 modules?
- [x]  Add yuidoc [#2106]
- [x] Improve yuidoc support #2106 is merged but we need more documentation.
- [ ] Passing options to CSS preprocessors #2010
- [x] Clarify how the resolver and the module system works #2145 
- [ ] Add examples to website showing how to generate nested routes/controllers see #2304 and  #2305

**Comment by knownasilya** [comment]
@kristianmandrup amd should be supported with ember-browserify addon and the deamdify transform.

**Comment by ulisesrmzroche** [comment]
Is this still going on? If so, I think I can close out the last two tasks.

**Comment by abuiles** [comment]
Closing in favor or #3307
