### ISSUE TITLE
enable pods by default

### ISSUE THREAD

**Issue by EndangeredMassa** [ember-cli/ember-cli#2646]
This is a tracking issue for making pods awesome enough to be enabled by default!

[Pod Structure Docs](http://www.ember-cli.com/#pod-structure)

---

**TO DO**

- [ ] [#1634](https://github.com/stefanpenner/ember-cli/issues/1634) [bug] templates in addons cannot use pod structure
- [ ] [#2561](https://github.com/stefanpenner/ember-cli/issues/2561) [enhancement] enable watching style files in pod structure
- [ ] [enhancement] allow new apps to start with pods via: `ember new --pod` or `ember init --pod`
- [ ] [enhancement] `ember g --help` should show which generators accept the `--pod` option
- [ ] [#2652](https://github.com/stefanpenner/ember-cli/issues/2652) [discussion] how should we handle [`config.usePodsByDefault`](https://github.com/stefanpenner/ember-cli/pull/2514)
- [ ] [#2653](https://github.com/stefanpenner/ember-cli/issues/2653) [discussion] which blueprints should support the pod structure?
- [ ] [#2654](https://github.com/stefanpenner/ember-cli/issues/2654) [discussion] should file names include some part of the path to avoid ambiguity in editors?
- [ ] [#2655](https://github.com/stefanpenner/ember-cli/issues/2655) [discussion] how will the [Ember 2.0 RFC](https://github.com/emberjs/rfcs/pull/15) affect pods?

---

If you want something else to be added or fixed for awesome pod support, please mention it here. Once all items here are complete, we can talk about when/how/if to enable it by default!

**Comment by stefanpenner** [comment]
cc @locks

**Comment by locks** [comment]
cc @trabus

**Comment by IanVS** [comment]
I'm a little confused about the status of pods these days.  Has there been any convergence of opinion over how they should be structured?  If I'm starting an app today, am I going to be using a structure that is outdated in a month?

**Comment by elliotlarson** [comment]
@IanVS :+1:  I'm confused about this too.

**Comment by stefanpenner** [comment]
> If I'm starting an app today, am I going to be using a structure that is outdated in a month?

go for pods, and report back issues.

**Comment by stefanpenner** [comment]
this issue seems to have gone stale, keeping tracking issues like this open doesn't really provide value.

We do plan to make this transition, but right now this issue is just noise.
