### ISSUE TITLE
enable async/await/generators meta issue

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#3529]
- [ ] babel/ember-cli
  - [x] fix options issue to enable experimental (ember-cli-babel -> https://github.com/babel/ember-cli-babel/commit/e5f97bb957bde67aa8628d188ef4b2df2208669b released with [v4.3.0](https://github.com/babel/ember-cli-babel/commit/8d0f971ce612ec3ad204fdafaaed88cc4bac0334))
  - [x] get babel to add a whitelist/optional for async / await as a more granular option
  - [ ] bundle polyfills on demand https://github.com/babel/ember-cli-babel/issues/24
    - [ ] patch for RSVP
- [x] replace JSHint with ESLint (https://github.com/ember-cli/ember-cli/issues/6501)
- [ ] co-routines should use Ember.RSVP.Promise
  - [ ] smash global (to prove it works)
  - [ ] implement our own co-routines + get babel to emit (like it does for bb)

why? because, writing test code like this is much better (Eventually we can drop large chunks of ember-testing)

example app: https://github.com/stefanpenner/ember-jobs

![screen shot 2015-03-13 at 5 45 28 pm](https://cloud.githubusercontent.com/assets/1377/6649500/db567d70-c9a8-11e4-9c60-ca369cd8e130.png)

app code isn't to bad either:

![screen shot 2015-03-13 at 5 46 43 pm](https://cloud.githubusercontent.com/assets/1377/6649506/efa10980-c9a8-11e4-9b90-4ee0ed566953.png)

![screen shot 2015-03-13 at 5 47 24 pm](https://cloud.githubusercontent.com/assets/1377/6649511/0609fd94-c9a9-11e4-9662-d4bd52841256.png)

**Comment by trabus** [comment]
If there is any busywork around this that you'd like to pass off, I'm interested!

**Comment by stefanpenner** [comment]
@trabus we really need jshint to understand this syntax, even if it is a fork of jshint until its ready. There are several PR's that implement it.

Now as for the automatic polyfil inclusion, I think we should come up with an RFC to re-think how ember-cli composes apps and addons so we can better accomplish this. I have some ideas here, just having a hard time coalescing my thoughts.  Tomorrow I'm working with @chadhietala on transitioning to npm (dropping bower) and I think it has some overlapping needs.

I will have my thoughts in RFC form by tomorrow night or wednesday morning. At which time I would love thoughts and feedback. If you have ideas to explore related to this before then, please don't hesitate. The more input later this week we can get the better.

Finally, the scheduler for RSVP shouldn't be to tricky, but will require some RSVP internals knowledge, that I can share if you are interested in pursuing it.

**Comment by IanVS** [comment]
Has any thought been given to using ESLint rather than JSHint? It supports this syntax no-problem, and is much more flexible / customizable.

**Comment by stefanpenner** [comment]
> Has any thought been given to using ESLint rather than JSHint? It supports this syntax no-problem, and is much more flexible / customizable.

Ya i've been tempted, if jshint doesn't catch up I will likely consider the switch.

**Comment by IanVS** [comment]
I asked about `async/await` here: https://github.com/jshint/jshint/issues/1939#issuecomment-77899370 and the answer did not sound promising for anything to be done any time soon.

**Comment by IanVS** [comment]
Also, JSHint is removing all of their code-style checks and telling people to use JSCS for them.  Seems like it would be a lot easier (and faster?) to run one linter instead of two.  Several of the options in the current ember-cli `.jshintrc` are deprecated:

- camelcase
- immed
- newcap 
- noempty 
- quotmark 
- laxbreak 
- sub 

Are all currently deprecated and will be removed in the next version of JSHint.

**Comment by stefanpenner** [comment]
> Also, JSHint is removing all of their code-style checks and telling people to use JSCS for them. Seems like it would be a lot easier (and faster?) to run one linter instead of two. Several of the options in the current ember-cli .jshintrc are deprecated:
> 
> camelcase
> immed
> newcap
> noempty
> quotmark
> laxbreak
> sub
> Are all currently deprecated and will be removed in the next version of JSHint.

this seems like a good point to raise, but not in the context of this issue as it appears mostly unrelated.

**Comment by IanVS** [comment]
Apologies. I'll create a separate issue for it.

**Comment by teddyzeenny** [comment]
@IanVS I moved the Ember Inspector to ESLint to be able to use async/await: https://github.com/emberjs/ember-inspector/pull/340 (it's an ember-cli app)

**Comment by mohamnag** [comment]
Is this planned to be done any time soon? I'm using async/await on an express server using babel successfully and would really appreciate it if same pattern could be applied to client side code.

**Comment by stefanpenner** [comment]
@mohamnag it is already possible, just not entirely automatic.

just add: https://github.com/stefanpenner/ember-jobs/blob/master/app/index.html#L20-L23 + https://github.com/stefanpenner/ember-jobs/blob/master/Brocfile.js#L7-L12

We are more or less waiting for async/await to hit stage 4 so that we know its not going to change, and libraries like JSHINT implement them. Once that happens we will likely make sure its more automatic the the above two stops.

**Comment by mohamnag** [comment]
thanks thats great news!

**Comment by stefanpenner** [comment]
jshint folks are open to a PR, assuming someone wants to push one of them to completion, we can then begin making it trivial on our end.

**Comment by stefanpenner** [comment]
Basically, I think we are going to make the switch to eslint and call it a day.

@Turbo87 your on-board with that correct?

**Comment by rwjblue** [comment]
Yes, that has also been my plan (RE: testing RFC).

**Comment by Turbo87** [comment]
In general yes, but there a still a few remaining pieces that are hardcoded to jshint which we need to address first

**Comment by stefanpenner** [comment]
@Turbo87 is there a tracking issue?

**Comment by Turbo87** [comment]
I don't think so. Example of what I was talking about: https://github.com/ember-cli/ember-cli/pull/5895

**Comment by givanse** [comment]
The snippet from https://github.com/ember-cli/ember-cli/issues/3529#issuecomment-165030263 results in `Unexpected token`

**Comment by sescobb27** [comment]
given that `RSVP` polyfill isn't here yet, how do you guys would implement something like this without `RSVP.all`? or that isn't possible right now?. thanks
```js
let details = await order.get('details');
return Ember.RSVP.all(details.map((detail) =>  detail.get('product')));
```

**Comment by stefanpenner** [comment]
> given that RSVP polyfill isn't here yet, how do you guys would implement something like this without RSVP.all? or that isn't possible right now?. thanks

I'm confused, RSVP is present?

**Comment by sescobb27** [comment]
sorry, I mean RSVP working with async/await. I would like to 
```js
let details = await order.get('details');
return Ember.RSVP.all(details.map((detail) =>  detail.get('product')));
```

**Comment by stefanpenner** [comment]
@sescobb27 it should "just work"

**Comment by buschtoens** [comment]
@stefanpenner So, looking at your [original comment](https://github.com/ember-cli/ember-cli/issues/3529#issue-61317702), is this basically done, since jshint is on its way out anyway?

**Comment by stefanpenner** [comment]
@buschtoens jshint isn't out yet, so its not quite done.

**Comment by buschtoens** [comment]
@stefanpenner Thanks for the insight. So, if I understand correctly, when I replace `ember-cli-jshint` with `ember-cli-eslint` I'd basically be good to go and everything should just work :tm: ?

**Comment by Turbo87** [comment]
@buschtoens more or less, yes

see https://github.com/ember-cli/ember-cli/issues/6501 for the JSHint -> ESLint replacement tracking issue

**Comment by Turbo87** [comment]
async/await works pretty well by now :)
