### ISSUE TITLE
EAK Feature Checklist

### ISSUE THREAD

**Issue by taras** [ember-cli/ember-cli#39]
## Tasks
- [x] **build:dist** - Build a minified & production-ready version of your app.
- [x] **build:debug** - Build an unminified version of your app for development and testing
- [x] **default** - Build (in debug mode) & test your application.
- [x] **server** - Run your server in development mode, auto-rebuilding when files change.
- [x] **serve:dist** - Build and preview a minified & production-ready version of your app.
- [x] **test** - Run your apps’s tests once. Uses Google Chrome by default.
- [x] **test:ci** - Run your app’s tests in PhantomJS. For use in continuous integration (i.e. Travis CI).
- [x] **test:browsers** - Run your app’s tests in multiple browsers (see tasks/options/testem.js for configuration).
- [x] **test:server** - Alias to `testem:run:basic`. Be sure to install testem first using `npm install -g testem`
### Scripts
- [x] JavaScript (js)
- [x] CoffeeScript (coffee)
- [ ] EmberScript (em)
### Templates
- [x] Handlebars (hbs, handlebars)
- [ ] Hogan (hjs)
- [x] Emblem (emblem)
### Styles
- [x]  SASS (sass, scss)
- [x]  LESS (less)
- [x] Stylus (styl)
- [x] css
### Images (png, jpg, jpeg)
- [ ] sprites
### JavaScript
- [x] Sourcemaps generation
- [x] JSHint validation
- [ ] Cache busting with file revision
- [x] Validate imports
### Styles
- [ ] CSS Prefix
- [ ] Cache busting with file revision
### HTML
- [ ] Minification
- [ ] Preprocess
## Server
- [x] LiveReload
### Basic
- [x] PhantomJS
- [x] Chrome
### Browsers
- [x] PhantomJS
- [x] Chrome
- [x] ChromeCanary
- [x] Firefox
- [x] Safari
- [x] IE7
- [x] IE8
- [x] IE9
## Customization
- [ ] Project specific tasks
