### ISSUE TITLE
Migrating ember-cli to a generalized development/build tool

### ISSUE THREAD

**Issue by trek** [ember-cli/ember-cli#5163]
I'm slowing working away at making ember-cli more general for use as an application or library development/build tool. The impetus for this is missing all the niceties of ember-cli when working in other environments and to avoid the need for forked projects like https://github.com/angular/angular-cli.

Instead, `?-cli` could provide tooling around all the common tasks for building project for the web. New projects could use this tool directly (a la Yeoman) or wrap with their own interface (more like angular-cli)

### Todos:

- [x] Allow installation of git remote blueprints (#2103)
- [x] Remove generated directory on ember new failure (#5144)
- [ ] Make package.json optional in project blueprints (#5146)
- [ ] Make bower.json optional in project blueprints (#5146)
- [ ] Make template processors optional (in progress)
- [ ] Make name of build file configurable
- [ ] Allow project blueprints have its own package.json
- [ ] Make dep isntall an afterInstall hook in the package.json
- [ ] Make `EmberApp` a descendent of a more generic class
- [ ] Make src (a.k.a. app) and test directories configurable

**Comment by spectras** [comment]
Hallelujah!
This is definitely an major step forward.
Would you mind checking out http://discuss.emberjs.com/t/application-integration-and-ember-cli/9148?
No answer needed, but that is an example of integration needs: the question “how to integrate `ember-cli` into a development ecosystem” lacks a clear answer as of today.

**Comment by listepo** [comment]
yeoman as generator +1

**Comment by stefanpenner** [comment]
> yeoman as generator +1

@listepo I don't think you read this issue...

**Comment by stefanpenner** [comment]
this seems to have gone stale, RFC seems most appropriate. 

An issue like this can remain open if an active champion is present.

**Comment by martndemus** [comment]
@stefanpenner / @trek I would like to get this going again. Would opening an RFC be a good first step towards this?

**Comment by nathanhammond** [comment]
@martndemus Yes! We'd love to think through the design with you. I recommend biting off small pieces, one at a time rather than trying to boil the ocean. :smile:

**Comment by martndemus** [comment]
If at all possible. Can we set up a short hangout to discuss?

**Comment by stefanpenner** [comment]
There are several people who are interested. Cc @searls  and others. Ya we should setup some sort of sync up hangout

**Comment by searls** [comment]
:+1: I am in.

**Comment by aciccarello** [comment]
Did a hangout/rfc ever get setup?

**Comment by aciccarello** [comment]
Also related: #5451
