### ISSUE TITLE
Test Coverage Mega Thread

### ISSUE THREAD

**Issue by kellyselden** [ember-cli/ember-cli#5487]
There are some areas that are missing test coverage. This will track any we find. This is a perfect place for new contributors to start understanding the code. Link pull requests next to its check mark.
- [ ] We could use an "acceptance/addon-test.js" file, similar to ["acceptance/new-test.js"](https://github.com/ember-cli/ember-cli/blob/master/tests%2Facceptance%2Fnew-test.js)
- [x] #5488 We need a test for 'doesn\'t allow to create an addon named `Ember`' (borrow from [here](https://github.com/ember-cli/ember-cli/blob/master/tests%2Funit%2Fcommands%2Fnew-test.js#L56))
- [x] #5488 We need a test for 'doesn\'t allow to create an addon named `ember-cli`' (borrow from [here](https://github.com/ember-cli/ember-cli/blob/master/tests%2Funit%2Fcommands%2Fnew-test.js#L65))
- [x] #5490 We need a test for 'shows a suggestion messages when the addon name is a period' (borrow from [here](https://github.com/ember-cli/ember-cli/blob/master/tests%2Funit%2Fcommands%2Fnew-test.js#L101)) (also, message needs to change to "addon")
- [x] #5873 We need a test for 'registers blueprint options in beforeRun' for addons (borrow from [here](https://github.com/ember-cli/ember-cli/blob/master/tests%2Funit%2Fcommands%2Fnew-test.js#L110))
- [ ] We need a test for 'passes command options through to init command' for addons (borrow from [here](https://github.com/ember-cli/ember-cli/blob/master/tests%2Funit%2Fcommands%2Fnew-test.js#L124))
- More to come... If you find any untested features, feel free to add to this list!

**Comment by Turbo87** [comment]
make sure to check #5483 before working on any of those issues and just copy pasting other text cases!

**Comment by courajs** [comment]
I don't really understand either of
> - [ ] We need a test for 'registers blueprint options in beforeRun' (borrow from here)
- [ ] We need a test for 'passes command options through to init command' (borrow from here)

It looks like you're suggesting to add tests that already exist?

**Comment by robbiepitts** [comment]
Added a PR (#5873) for:

> - [ ] We need a test for 'registers blueprint options in beforeRun' (borrow from here)

**Comment by kellyselden** [comment]
@courajs I updated the text. I forgot the addon references.

**Comment by Turbo87** [comment]
@kellyselden is this still up-to-date?

**Comment by locks** [comment]
Closing this due to inactivity. A new assessment and issue should be done if we want to improve this further!
