### ISSUE TITLE
Linters not running on addon files

### ISSUE THREAD

**Issue by alexlafroscia** [ember-cli/ember-cli#5498]
I'm one of the maintainers of [`ember-ajax`](https://github.com/ember-cli/ember-ajax) and am working on upgrading the addon to use Ember CLI`2.3.0`.  I noticed that some of the file were being linted before are no longer being linted after upgrading from `1.13.15`.  Specifically, any of the files that are inside the `addon` directory are now being ignored, both by JSHint and JSCS (through `ember-suave`) although all of the other files are still being handled correctly.

I took the outputs of `ember test` for both versions, cleaned up the output to make them comparable, and the diff can be found [here](https://www.diffchecker.com/zvdrblyf).  There are two new lines in the `2.3.0` file, which are expected, but the missing lines are unexpected.

## Todo

- [x] Add method as mentioned in https://github.com/ember-cli/ember-cli/issues/5498#issuecomment-191798300
- [x] Unit test `_eachProjectAddonInvoke` method
- [x] Add an addon smoke test confirming that ember test fails when an addon's addon/ tree.

**Comment by alexlafroscia** [comment]
I just updated `ember-ajax` to the `2.4.1` release from today, and am still seeing the same issue with the `addon/` files not being linted as part of `ember test`.

**Comment by rwjblue** [comment]
OK, so this issue was introduced by https://github.com/ember-cli/ember-cli/pull/5432.  In that PR I suggested that we use `this.eachAddonInvoke('lintTree'`from the `jshintAddonTree` method, however I believe that `this.addons` from within an addon under development only includes the addons actual `dependencies` and not the `devDependencies`.  Obviously, an addon wouldn't want to list its testing deps in `dependencies`, so that invocation returns an empty array of trees and therefore causes this issue.

**Comment by rwjblue** [comment]
The solution is to do something like (which could be called `eachProjectAddonInvoke`:

```
Addon.prototype.eachProjectAddonInvoke = function eachProjectAddonInvoke(methodName, args) {
  this.initializeAddons();

  var invokeArguments = args || [];

  return this.project.addons.map(function(addon) {
    if (addon[methodName]) {
      return addon[methodName].apply(addon, invokeArguments);
    }
  }).filter(Boolean);
};
```

Then using `this.eachProjectAddonInvoke` instead of `this.eachAddonInvoke` in the `jshintAddonTree` method.

**Comment by rwjblue** [comment]
Rough hitlist for fixing this:

* Add method as mentioned in https://github.com/ember-cli/ember-cli/issues/5498#issuecomment-191798300
* Unit test `_eachProjectAddonInvoke` method
* Add an addon smoke test confirming that `ember test` fails when an addon's `addon/` tree.  This would look roughly similar to [this test](https://github.com/ember-cli/ember-cli/blob/e686c494ec4f99389150dae34566aca6a7bda45c/tests/acceptance/addon-smoke-test-slow.js#L157-L165) but use a different fixture path that contains some JSHint issues in `addon/` dir.

I won't have time to work on this in the next week, but I would be happy to help someone with any issues they encounter while implementing the fix layed out above....

**Comment by alexlafroscia** [comment]
Thanks! If you think this would be a good thing for someone new to take on, I'll try to dig into this myself.

**Comment by rwjblue** [comment]
Awesome, happy to help if you hit roadblocks (here in the issue, in slack, or whatever).

**Comment by rwjblue** [comment]
Hmm, I just noticed something.  We are not passing the correct arguments to `lintTree` when we do `eachAddonInvoke` ATM.  I'm testing in your ember-ajax branch, to see if that fixes the underlying issue...

**Comment by rwjblue** [comment]
OK, so that doesn't fix anything (but the change is still needed).

So:

```js
this.eachAddonInvoke('lintTree', [addonJs]);
```

Needs to become (once the new method is created):

```js
this.eachProjectAddonInvoke('lintTree', ['addon', addonJs]);
```

**Comment by alexlafroscia** [comment]
@rwjblue so, I wrote up the method as you described here, but I'm getting `this.project` as `undefined` during a few of the existing tests (not new ones that I've added).  Any thoughts on why that may be, or where to start looking?

**Comment by rwjblue** [comment]
As discussed in slack, those tests are just wrong.  The `Addon` constructor needs two args (those calls should most likely be `new FirstAddon(project, project)`).

> Also: did you want this method with the _ in front of the method name or no?

Yes, lets underscore it to ensure it is clearly private (we generally don't want addons invoking methods on other top-level addons)...

**Comment by alexlafroscia** [comment]
Alright, so I pushed an update to the previous commit that updates the acceptance-style test to use `.catch` to verify that the linting works.

One thing that I was unable to do was verify the output text the way you mentioned.  Inside the `catch` handler, `result.outputStream` didn't have any information about the actual test that failed, and there didn't seem to be any way to get the output from the `ember test` command.  The information on the test that failed gets output to the screen instead.
