### ISSUE TITLE
reduce bite-size/file-count of ember-cli and its dep.

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6147]
# why does this matter?

npm installs are dominate by:
- download times
- local IO moving/copying etc files around

By reducing this overhead, we help reduce both on-disk bytes, number on files, and improve install times. Etc.

It is also the case that many of our dependencies publish accidental files, or include extra dependencies. At scale, the cost becomes non-trivial

This will likely be a long running issue, we should likely get a task force together to address this.
## Stuff this aims to address
- download times
- untar/move times
- deletion times
- on-disk bytesize cost
- complexity?

somewhat related: #6137

Big offenders, we should make more aspects of ember pay as you go. For example:
- bower (accounts for like 20-30% of the dep size)

Another effort is to:
- tools/techniques to identify
- tests to prevent regressions cc @hjdivad 
## List of top-level deps + cost to us in # files:
- [x] broccoli-asset-rev 896: https://github.com/rickharrison/broccoli-asset-rev/issues/101
- [ ] ember-ajax 30
- [ ] ember-cli  27247 https://github.com/ember-cli/ember-cli/issues/6149
- [x] ember-cli-app-version 178  EmberSherpa/ember-cli-app-version#28
- [x] ember-cli-babel 5430 https://github.com/babel/ember-cli-babel/pull/83
- [ ] ember-cli-dependency-checker 98
- [x] ember-cli-htmlbars 1091 https://github.com/ember-cli/ember-cli-htmlbars/pull/87
- [ ] ember-cli-htmlbars-inline-precompile 21
- [ ] ember-cli-inject-live-reload 6
- [x] ember-cli-jshint 2063
- [ ] ember-cli-qunit 6167
- [ ] ember-cli-release 558
- [x] ember-cli-sri 515
- [ ] ember-cli-test-loader 8
- [x] ember-cli-uglify 1131 https://github.com/ember-cli/ember-cli-uglify/issues/11
- [ ] ember-data 6660 https://github.com/emberjs/data/issues/4492
- [ ] ember-export-application-global  15
- [ ] ember-inflector  27
- [ ] ember-load-initializers 11
- [ ] ember-resolver 83
- [x] ember-welcome-page  2288 https://github.com/ember-cli/ember-welcome-page/issues/33
- [ ] loader.js 36

discovered via npm v2 (although not totally accurate re: dupes, it helps pin-point costly roots):

```
for x in (ls) do
  echo $x
  find $x | wc -l
end
```

**Comment by stefanpenner** [comment]
Will update with more details and action items.

**Comment by musaffa** [comment]
[Flamegraph](http://www.brendangregg.com/flamegraphs.html) is an interesting tool for performance instrumentation. Sam Saffron has been using flamegraph to pin point the bottlenecks of discourse rails server. He has a [blog post](https://samsaffron.com/archive/2013/03/19/flame-graphs-in-ruby-miniprofiler) about performance instrumentation with flamegraph.

Nodejs has some implemenations of flamegraph, for example [stackvis](https://github.com/joyent/node-stackvis), [0x](https://github.com/davidmarkclements/0x).

**Comment by stefanpenner** [comment]
@musaffa yup a good tool, luckily this issue is specifically to remove extra bytes/files we download. So we can likely get away with just reduces the size and count of files downloaded

**Comment by stefanpenner** [comment]
# Plan of attack: -> divide and conquer

If you are interested in helping

1. pick anything in the list that appears to have wasteful files
2. mark a comment here or in the associated issue saying you are working on addressing
3. Submit a PR
4. Once merged / released, report back here in a comment and we can "complete the task"

Note: some of the above dependencies are not a problem, they are included here because we have not yet confirmed they are good. Once confirmed, report back here with "RSVP isn't including anything wasteful", and we will close it.


Stuff that can be changed
---

* add .gitingore to ignore extra files
* evaluate different dependencies that are more concise/focused e.g. `lodash` -> `lodash.uniq` if all you need is `unique`

**Comment by musaffa** [comment]
I'm removing that comment to a more related topic.

**Comment by Bockit** [comment]
Just making sure I understand the intent here. If I were to add the `files` property to loader.js and tell it to only include the files below, would that be what we're looking for? Right now everything else isn't needed by a loader.js install afaict.

```json
{
  "files": [
    "index.js",
    "lib/loader.js"
  ]
}
```

(package.json, README.md and LICENSE.md get included by default)

If so, I'll make a PR pronto, and then take a look at some others

**Comment by stefanpenner** [comment]
@Bockit sounds very reasonable.

**Comment by chrism** [comment]
PR submitted for: ember-welcome-page 2288 ember-cli/ember-welcome-page#33

**Comment by listochkin** [comment]
> bower (accounts for like 20-30% of the dep size)

@stefanpenner could we check whether a user has a globally installed Bower during the installation of Ember CLI and use that instead of relying on a local one? I can imagine it looking like this for a new Ember CLI user:

```
$ npm install -g ember-cli
\
Looks like you don't have Bower installed on your system.
Ember relies on Bower to download some of your app dependencies. 
Would you like to install it? (Y/n)
```

or

```
$ npm install -g ember-cli
\
The version of Bower you have installed on your system is outdated.
Ember relies on Bower to download some of your app dependencies.
Would you like to update Bower? (Y/n)
```
We could also check for bower version before running Bower-related tasks. Migration would involve switching from running Bower programmatically to calling it as a sub-command.

**Comment by stefanpenner** [comment]
@listochkin originally we did this, the problem was the number of broken/buggy in incompatible bower versions was so high, we made the call to provide a curated bundle instead.

**Comment by listochkin** [comment]
@stefanpenner could we have it _hidden_ somewhere in the global installation of Ember-CLI then? This way we could still curate it without copying it into each project.

**Comment by stefanpenner** [comment]
@listochkin this is also an interesting solution, I am in-favor. Although it would require someone to commit to it

**Comment by Turbo87** [comment]
> could we have it hidden somewhere in the global installation of Ember-CLI then? This way we could still curate it without copying it into each project.

we've dealt with people in the past though that don't install ember-cli globally and only rely on the per-project installation...

**Comment by alexlafroscia** [comment]
I'll look at `ember-ajax` and see if we can clean anything up there.

**Comment by cibernox** [comment]
@stefanpenner I've created a PR for `ember-cli-app-version`: https://github.com/EmberSherpa/ember-cli-app-version/pull/28

**Comment by cibernox** [comment]
And for `ember-cli-jshint`: https://github.com/ember-cli/ember-cli-jshint/pull/10

**Comment by alexlafroscia** [comment]
I wonder if we should consider making the change that @cibernox just made for `ember-cli-app-version` the default for new addons 🤔

**Comment by alexlafroscia** [comment]
@stefanpenner Does every addon need the dependency on `ember-cli-babel`?  Seems like that should be a `devDependency` but I don't want to go and remove it

**Comment by stefanpenner** [comment]
@alexdiliberto if they have babel to transform they should bring along their own babel. And if all the babels are the same, dedupe should handle.

**Comment by kratiahuja** [comment]
@stefanpenner : PR for loader.js https://github.com/ember-cli/loader.js/pull/93

**Comment by locks** [comment]
What to do about this?
https://github.com/ember-cli/ember-cli/blob/5d31cb49fc6d3105876bc6559d8c22b3afd9b23d/package.json#L68
https://github.com/ember-cli/ember-cli/blob/5d31cb49fc6d3105876bc6559d8c22b3afd9b23d/package.json#L91
https://github.com/ember-cli/ember-cli/blob/5d31cb49fc6d3105876bc6559d8c22b3afd9b23d/package.json#L93

**Comment by stefanpenner** [comment]
@locks we should

1. drop lodash
2. keep lodash.template (is only loaded on-demand)
3. keep lodash-subset (is loaded eagerly)

**Comment by jonkoops** [comment]
It might be an idea to remove .npmignore entirely from the `addon` generator in Ember CLI and replace it with the whitelist in the `files` key. That way most add-ons should get the behaviour we want out of the box.

**Comment by alobaidizt** [comment]
@stefanpenner PR for `ember-cli-sri` [jonathanKingston/ember-cli-sri](https://github.com/jonathanKingston/ember-cli-sri/pull/27) 🎆

**Comment by knownasilya** [comment]
```json
iradchenko ember-cli (master)$ slow-deps 
Analyzing 95 dependencies...
[====================] 100% 0.0s
-----------------------------------------------------------------
| Dependency                          | Time  | Size   | # Deps |
-----------------------------------------------------------------
| broccoli-babel-transpiler           | 12s   | 22 MB  | 0      |
| ember-try                           | 11.8s | 25 MB  | 0      |
| mocha-eslint                        | 11.1s | 10 MB  | 0      |
| ember-cli-legacy-blueprints         | 10.8s | 24 MB  | 0      |
| testem                              | 9s    | 11 MB  | 1      |
| npm                                 | 8.6s  | 11 MB  | 1      |
| yuidocjs                            | 7.6s  | 22 MB  | 1      |
| bower                               | 6.1s  | 15 MB  | 1      |
| ember-cli-preprocess-registry       | 5.8s  | 11 MB  | 0      |
| ember-cli-blueprint-test-helpers    | 5.7s  | 7.0 MB | 0      |
| ember-cli-broccoli                  | 5.5s  | 6.8 MB | 0      |
| istanbul                            | 5.2s  | 6.6 MB | 1      |
| ember-cli-internal-test-helpers     | 4.4s  | 3.0 MB | 0      |
| inquirer                            | 4.3s  | 8.6 MB | 0      |
| mocha                               | 3.8s  | 1.2 MB | 1      |
| nock                                | 3.6s  | 4.1 MB | 0      |
| broccoli-funnel                     | 3.5s  | 2.6 MB | 0      |
| broccoli-concat                     | 3.5s  | 2.1 MB | 0      |
| supertest                           | 3.3s  | 1.1 MB | 0      |
| broccoli-config-loader              | 3.2s  | 1.3 MB | 0      |
| express                             | 3.2s  | 1.2 MB | 0      |
| markdown-it-terminal                | 3.2s  | 2.3 MB | 0      |
| yuidoc-ember-cli-theme              | 3s    | 953 KB | 0      |
| broccoli-config-replace             | 2.9s  | 1.5 MB | 0      |
| broccoli-merge-trees                | 2.8s  | 2.6 MB | 0      |
| mocha-only-detector                 | 2.8s  | 406 KB | 1      |
| yam                                 | 2.7s  | 393 KB | 0      |
| tree-sync                           | 2.7s  | 2.2 MB | 0      |
| tiny-lr                             | 2.7s  | 1.2 MB | 0      |
| fs-extra                            | 2.7s  | 323 KB | 0      |
| broccoli-filter                     | 2.7s  | 1.3 MB | 0      |
| ember-cli-broccoli-sane-watcher     | 2.6s  | 1.8 MB | 0      |
| broccoli-plugin                     | 2.6s  | 955 KB | 0      |
| bower-config                        | 2.5s  | 634 KB | 0      |
| fs-tree-diff                        | 2.4s  | 1.5 MB | 0      |
| ora                                 | 2.4s  | 84 KB  | 0      |
| heimdalljs-logger                   | 2.3s  | 1.5 MB | 0      |
| github                              | 2.3s  | 916 KB | 0      |
| markdown-it                         | 2.2s  | 809 KB | 1      |
| compression                         | 2.2s  | 475 KB | 0      |
| leek                                | 2.1s  | 311 KB | 0      |
| chai-as-promised                    | 2s    | 465 KB | 1      |
| testdouble                          | 2s    | 1.7 MB | 0      |
| core-object                         | 2s    | 52 KB  | 0      |
| glob                                | 2s    | 156 KB | 0      |
| configstore                         | 1.9s  | 203 KB | 0      |
| portfinder                          | 1.9s  | 258 KB | 0      |
| proxyquire                          | 1.9s  | 142 KB | 0      |
| ember-cli-normalize-entity-name     | 1.9s  | 42 KB  | 0      |
| npm-package-arg                     | 1.9s  | 175 KB | 0      |
| sane                                | 1.9s  | 240 KB | 1      |
| morgan                              | 1.9s  | 131 KB | 0      |
| walk-sync                           | 1.9s  | 76 KB  | 0      |
| chalk                               | 1.7s  | 44 KB  | 0      |
| node-uuid                           | 1.7s  | 41 KB  | 1      |
| heimdalljs-fs-monitor               | 1.6s  | 1.2 MB | 0      |
| http-proxy                          | 1.5s  | 70 KB  | 0      |
| promise-map-series                  | 1.4s  | 183 KB | 0      |
| quick-temp                          | 1.4s  | 567 KB | 0      |
| semver                              | 1.4s  | 54 KB  | 1      |
| silent-error                        | 1.3s  | 38 KB  | 0      |
| find-up                             | 1.3s  | 26 KB  | 0      |
| multiline                           | 1.3s  | 19 KB  | 0      |
| chai                                | 1.3s  | 434 KB | 0      |
| temp                                | 1.3s  | 40 KB  | 0      |
| nopt                                | 1.2s  | 38 KB  | 1      |
| minimatch                           | 1.2s  | 59 KB  | 0      |
| rsvp                                | 1.1s  | 178 KB | 0      |
| broccoli-funnel-reducer             | 1.1s  | 8.3 KB | 0      |
| lodash.template                     | 1.1s  | 55 KB  | 0      |
| git-repo-info                       | 1.1s  | 57 KB  | 0      |
| ember-cli-string-utils              | 1s    | 5.9 KB | 0      |
| chai-files                          | 1s    | 27 KB  | 0      |
| exists-sync                         | 1s    | 8.3 KB | 0      |
| filesize                            | 1s    | 15 KB  | 0      |
| eslint-plugin-chai-expect           | 990ms | 8.0 KB | 0      |
| through                             | 984ms | 14 KB  | 0      |
| debug                               | 969ms | 36 KB  | 0      |
| resolve                             | 959ms | 52 KB  | 0      |
| exit                                | 958ms | 64 KB  | 0      |
| inflection                          | 939ms | 62 KB  | 0      |
| node-modules-path                   | 935ms | 9.6 KB | 0      |
| symlink-or-copy                     | 928ms | 9.6 KB | 0      |
| clean-base-url                      | 927ms | 2.6 KB | 0      |
| amd-name-resolver                   | 923ms | 5.5 KB | 0      |
| diff                                | 899ms | 333 KB | 0      |
| isbinaryfile                        | 895ms | 8.6 KB | 0      |
| broccoli-source                     | 849ms | 7.1 KB | 0      |
| ember-cli-lodash-subset             | 832ms | 34 KB  | 0      |
| escape-string-regexp                | 808ms | 4.0 KB | 0      |
| get-caller-file                     | 801ms | 3.1 KB | 0      |
| is-git-url                          | 797ms | 5.4 KB | 0      |
| ember-cli-get-component-path-option | 772ms | 3.2 KB | 0      |
| ember-cli-is-package-missing        | 757ms | 2.4 KB | 0      |
| bower-endpoint-parser               | 725ms | 24 KB  | 0      |
-----------------------------------------------------------------
Total time (non-deduped): 4m 12.6s
Total size (non-deduped): 226 MB
```

This might help a little, used https://github.com/nolanlawson/slow-deps

**Comment by jonkoops** [comment]
@knownasilya I would like to stress again that adding an .npmignore is not needed when using the files whitelist in package.json. Not to mention a lot more future proof.

**Comment by knownasilya** [comment]
Yeah, @Turbo87 reminded me promptly 👍

**Comment by twokul** [comment]
this one is largely done and not particularly actionable at this point. closing.
