### ISSUE TITLE
This project appears to introduce 27247 files via itself and its deps

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli#6149]
[PLAN OF ATTACK](https://github.com/ember-cli/ember-cli/issues/6147#issuecomment-237439212)

big offenders:
--------------

- [ ] bower    5021 we are on an old version... we should likely  (extract as addon, update, fork our own subset)??
- [ ] broccoli-babel-transpiler 3725 https://github.com/babel/broccoli-babel-transpiler/issues/90
- [ ] npm 4230 (we are still on an old version, we should likely work hard to upgrade asap, then investigate)

the rest (long tail but adds up) :
-----

- [x] amd-name-resolver 13 https://github.com/chadhietala/amd-name-resolver/pull/8
- [ ] bower-config 700 
- [ ] bower-endpoint-parser 11
- [x] broccoli-concat 546 https://github.com/ember-cli/broccoli-concat/issues/72
- [ ] broccoli-config-loader 213 https://github.com/ember-cli/broccoli-config-loader/issues/5
- [ ] broccoli-config-replace 408 https://github.com/ember-cli/broccoli-config-replace/issues/6
- [ ] broccoli-funnel 343 https://github.com/broccolijs/broccoli-funnel/issues/72
- [x] broccoli-funnel-reducer 5 https://github.com/ember-cli/broccoli-funnel-reducer/pull/1
- [x] broccoli-merge-trees 325 https://github.com/broccolijs/broccoli-merge-trees/issues/47
- [x] broccoli-sane-watcher 14 https://github.com/broccolijs/broccoli-sane-watcher/issues/33
- [x] broccoli-source 8 https://github.com/broccolijs/broccoli-source/pull/2
- [x] broccoli-viz 13 https://github.com/stefanpenner/broccoli-viz/pull/23
- [x] chalk 38
- [x] clean-base-url 4 https://github.com/ember-cli/clean-base-url/pull/1
- [x] compression 71
- [x] configstore 160
- [ ] core-object 30 https://github.com/ember-cli/core-object/issues/41
- [ ] debug 20
- [ ] diff 38
- [ ] ember-cli-broccoli 778 helped by https://github.com/ember-cli/broccoli/pull/5
- [x] ember-cli-get-component-path-option 5 https://github.com/ember-cli/ember-cli-get-component-path-option/pull/2
- [x] ember-cli-is-package-missing 3
- [x] ember-cli-legacy-blueprints 1040 https://github.com/ember-cli/ember-cli-legacy-blueprints/pull/47
- [x] ember-cli-normalize-entity-name 4 https://github.com/ember-cli/ember-cli-normalize-entity-name/pull/2
- [ ] ember-cli-preprocess-registry 1267 https://github.com/ember-cli/ember-cli-preprocessor-registry/issues/15
- [x] ember-cli-string-utils 3
- [ ] ember-try 898 https://github.com/ember-cli/ember-try/issues/88
- [x] escape-string-regexp 5
- [x] exists-sync 8 https://github.com/ember-cli/exists-sync/pull/3
- [ ] exit 25
- [ ] express 332
- [x] filesize 10
- [ ] find-up 22
- [x] fs-extra 130
- [x] fs-monitor-stack 4 https://github.com/stefanpenner/fs-monitor-stack/pull/3
- [ ] fs-tree-diff 49 https://github.com/stefanpenner/fs-tree-diff/issues/28
- [x] get-caller-file 10 https://github.com/stefanpenner/get-caller-file/issues/1
- [x] git-repo-info 134 https://github.com/rwjblue/git-repo-info/issues/21
- [x] glob 43
- [x] http-proxy 29
- [x] inflection 10
- [ ] inquirer 187 https://github.com/SBoudrias/Inquirer.js/pull/403
- [x] is-git-url 5
- [ ] isbinaryfile 35
- [x] leek 811 https://github.com/twokul/leek/issues/33
- [x] lodash 1023 (old, master includes ember-cli-lodash-subset)
- [x] markdown-it 179
- [ ] markdown-it-terminal 443 https://github.com/trabus/markdown-it-terminal/pull/8
- [x] minimatch 27
- [x] morgan 45
- [x] node-modules-path 16 https://github.com/ember-cli/node-modules-path/pull/4
- [ ] node-uuid 20 https://github.com/broofa/node-uuid/issues/143
- [ ] nopt 20 https://github.com/npm/nopt/issues/69
- [ ] npm-package-arg 29 https://github.com/npm/npm-package-arg/issues/20
- [x] ora 38
- [x] portfinder 78 https://github.com/indexzero/node-portfinder/issues/36
- [x] promise-map-series 9 https://github.com/joliss/promise-map-series/issues/8
- [x] quick-temp 68
- [ ] resolve 124  https://github.com/substack/node-resolve/issues/105
- [x] rsvp 40
- [x] sane 119 https://github.com/amasad/sane/issues/71
- [ ] semver 8
- [x] silent-error 4
- [x] symlink-or-copy 11 https://github.com/broccolijs/node-symlink-or-copy/pull/24
- [ ] temp 36 https://github.com/bruce/node-temp/issues/56
- [x] testem 2058 https://github.com/testem/testem/issues/950
- [x] through 13 https://github.com/dominictarr/through/issues/44
- [x] tiny-lr 317 https://github.com/mklabs/tiny-lr/issues/106
- [x] tree-sync 141 https://github.com/stefanpenner/tree-sync/issues/12
- [x] walk-sync 20 https://github.com/joliss/node-walk-sync/pull/28
- [x] yam 291

----

bower & npm most likely should be independently audited, see if we can do some cleanup to fix them up. These are both actually unfortunate dependencies that exist so we can ensure a bug resistent/consistent and quality "install" experience for our users. But, I would love a future where that could be avoided all together. In the short term i believe we could make bower and optional (and install on-demand) dependency. npm is trickier.

----

> Whitelist package files stefanpenner/tree-sync#12

**Comment by TheLarkInn** [comment]
Interestingly enough I know this may not be the best place to slip in a suggestion for a different build system, but u believe compared to the broccoli stuff y'all have here, maybe the exploration of webpack as a bundler is worth the conversation. We did the same with the angular-cli, and a lot of _modules_ were shed off the list pretty quickly thanks to all the out of the box tools in Webpack.

**Comment by stefanpenner** [comment]
Plan of attack: -> divide and conquer

If you are interested in helping

1. pick anything in the list that appears to have wasteful files
2. mark a comment here or in the associated issue saying you are working on addressing
3. Submit a PR
4. Once merged / released, report back here in a comment and we can "complete the task"

Note: some of the above dependencies are not a problem, they are included here because we have not yet confirmed they are good. Once confirmed, report back here with "RSVP isn't including anything wasteful", and we will close it.

**Comment by stefanpenner** [comment]
The main issue: https://github.com/ember-cli/ember-cli/issues/6147

**Comment by stefanpenner** [comment]
@TheLarkInn thank you for the offer, but we will continue to use and improve our existing tool chain.

**Comment by TheLarkInn** [comment]
No problem just wanted to make sure you guys know that we are more than happy to help give our time if it a decision you make in the future. Keep up the good work!!!

**Comment by Turbo87** [comment]
https://github.com/ember-cli/ember-cli-legacy-blueprints/issues/42 should reduce the dependency impact of ember-cli-legacy-blueprints

**Comment by rwwagner90** [comment]
How close are we to being able to nuke bower altogether?

**Comment by rtablada** [comment]
@rwwagner90 due to addons I would say at least a full major version of saying that bower use is deprecated and warn.

**Comment by stefanpenner** [comment]
@rwwagner90 

https://github.com/ember-cli/ember-cli/pull/5921 + https://github.com/emberjs/ember.js/pull/13022 + backwards compat in ember-cli if the ember-core npm module was not provided

But remember, we will have to re-install the optional bower dependency for a long time, as many addons need it. Which leads me to believe we must do both (improve our version of bower, and remove it from the default environment).

**Comment by Turbo87** [comment]
the following are somewhat related to this issue but don't look like they will be resolved any time soon... 😞 

- https://github.com/substack/node-mkdirp/pull/101
- https://github.com/substack/minimist/pull/95

**Comment by stefanpenner** [comment]
@Turbo87 ya..

**Comment by dguettler** [comment]
@stefanpenner "Remove unused dependencies #15" was in regards to `yam`

**Comment by locks** [comment]
I have verified [ember-cli-is-package-missing](https://github.com/ember-cli/ember-cli-is-package-missing/blob/master/package.json#L6-L8).

**Comment by dguettler** [comment]
@stefanpenner ^ are couple more package updates

**Comment by dguettler** [comment]
dominictarr/through#44 was rejected by the author, he includes all files by his policy

**Comment by dguettler** [comment]
Verified [ora](https://github.com/sindresorhus/ora/blob/master/package.json#L18-L20)

**Comment by bmeurant** [comment]
created a PR for testem & lodash testem/testem#950. Other testem deps are still to verify

**Comment by dguettler** [comment]
@stefanpenner when you get a chance can you update the checklist with open PRs

**Comment by eriktrom** [comment]
portfinder has been bumped, it can be checked off

Thanks @dguettler for the work of updating all these repos 💯

**Comment by stefanpenner** [comment]
Although not 100% complete (likely not possible), I believe this meta issue has been wildly successful. Thanks to all the contributors! We may do another issue like this in the future again
