### ISSUE TITLE
Module Unification Epic

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli#6332]
The [Module Unification RFC](https://github.com/emberjs/rfcs/pull/143) is all but merged. So this week @iezer @mitchlloyd @bantic and I tried to get the ball rolling. And rolling it is! Two important links:
- We forked the [ember-cli/ember-resolver](https://github.com/ember-cli/ember-resolver) repo to  [201-created/dangerously-set-unified-resolver](https://github.com/201-created/dangerously-set-unified-resolver) in which a new `unified-resolver` has been added. You can [view a diff](https://github.com/ember-cli/ember-resolver/compare/master...201-created:master) of the work. This addon both implements a 100% dynamic version of the module unification rules and gets ember-cli building the `src/` dir.
- In [201-created/--new-app-blueprint#with-danger](https://github.com/201-created/--new-app-blueprint/tree/master) we have a demo application using this addon (you need to `npm link` the `dangerously-set-unified-resolver` addon into place). Again you can [view a diff](https://github.com/rwjblue/--new-app-blueprint/compare/master...201-created:master) of this work, note that the application isn't really doing much.

This implementation works for a proof of concept, however there are several next steps that need to happen before this work is really production ready. Our list, surely missing many important items, follows:
- [x] ~~The addon as written is 100% dynamic. This is probably not going to be great for production, and we will want to do part of this work at compile time on the server.~~ This is changed by picking an appropriate `ModuleResolver`. It seems ok to ship with the `RequireJSModuleResolver` and to adopt the precompiled one later.
- [x] ~~Should the resolver simply fail to resolve unknown types silently, or should they be explicitly defined? We've explicitly defined several Ember types (for example [`-view-registry`](https://github.com/201-created/dangerously-set-unified-resolver/blob/master/addon/ember-config.js#L35) that seem like they could be handled with general fallback behavior.~~ These issues have been teased out in glimmer-di
- [x] The old resolver tests are failing in our system- not because anything was changed, we just altered the env in some way. @iezer might know more here.
- [x] ~~Ember-CLI requires the `app/styles` directory be present per [ember-app.js](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L1306). This needs to change upstream.~~ This is tracked in https://github.com/ember-cli/ember-cli/pull/6908
- [x] ~~In Ember-CLI `this.trees.app` is too contstraining- it only permits us to look in a single place for `index.html` [for example](https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/ember-app.js#L656), when the new resolver rules suggest we should look in `src/ui/` first.~~ This is tracked in https://github.com/ember-cli/ember-cli/pull/6908
- [x] ~~The new resolver should be used when an Ember app has a `src` dir present, however the new resolver should also fall back to the current `ember-resolver` implementation so you can migrate from the `app/` dir to the `src/` dir incrementally.~~ Tracked at https://github.com/ember-cli/ember-resolver/issues/188
- [x] ~~Templates currently compile with a `default` export, meaning you can only name them `${name}/${type}.hbs`. The compiler needs to know it can export `template` when the file is just named `${name}` (or that it should output to the `${name}/${type}` module path).~~ tracked at https://github.com/ember-cli/ember-resolver/issues/189
- [ ] The resolver is currently accepts a one-time configuration, however addons need an API to add collections and types. This should be as declarative as possible within reason- addons can add setup but cannot introspect the existing config.
- [ ] The resolver addon should lint/error on bad filesystem layouts. This needs to be broken down into detailed cases and tests.
- [ ] The [`expandLocalLookup`](https://github.com/201-created/dangerously-set-unified-resolver/blob/master/tests/unit/unified-resolver/expand-local-lookup-test.js) tests should probably be refactored to be more DRY, akin to the [basic-dynamic-tests](https://github.com/201-created/dangerously-set-unified-resolver/blob/master/tests/unit/unified-resolver/basic-dynamic-test.js).

Additionally there are a few items needed before actual release:
- [ ] Make the new resolver log when ENV.APP.LOG_RESOLVER = true
- [ ] Update blueprints to use the new structure
- [x] Need to implement an [example addon](https://github.com/dgeb/rfcs/blob/module-unification/text/0000-module-unification.md#example-addon) and support both old and new addon structures. Partially handled via recent work to fallback to old resolver.

Would love thorough review by @dgeb and @rwjblue and others, and I'm sure we should set up some further meetings to figure out a plan.

**Comment by bantic** [comment]
🙌 
couple of those links above seem to be borked, here they are:
  * the fork of ember-resolver, called ["dangerously-set-unified-resolver"](https://github.com/201-created/dangerously-set-unified-resolver)
  * [demo application using the addon](https://github.com/201-created/--new-app-blueprint/tree/with-danger)

**Comment by mixonic** [comment]
Darn markdown :-p Thanks @bantic I fixed them inline as well.

**Comment by iezer** [comment]
The 3rd bullet about old tests is done.

**Comment by iezer** [comment]
A few other tasks:
 - [ ] Make the new resolver log when `ENV.APP.LOG_RESOLVER = true`
 - [ ] Update blueprints to use the new structure
 - [ ] Need to implement [Example Addon](https://github.com/dgeb/rfcs/blob/module-unification/text/0000-module-unification.md#example-addon) and support both old and new addon structures. Partially handled via recent work to fallback to old resolver.

**Comment by mixonic** [comment]
I've added @iezer's comments to the issue description

**Comment by stefanpenner** [comment]
@mixonic is it possible to transfer this to an ember-cli RFC or something. It seems like how to implement requires design and discussion.

**Comment by mixonic** [comment]
@stefanpenner I don't think an RFC would be appropriate for a todo list. I believe @tomdale was going to pick up an implementation RFC per your request.

**Comment by stefanpenner** [comment]
@mixonic alright, then it is likely "in addition" to the above list?

**Comment by paulyoder** [comment]
@mixonic  Any updates on the progress of this feature? I'm not complaining; I'm just excited to see this feature released

**Comment by mixonic** [comment]
@dgeb has been pushing this work forward in some other repos- the build-time compilation and such is being experimented with on top of a replacement for the current container.

**Comment by mansona** [comment]
Hi folks 👋 

I know we are still very early days on all of this work but I wanted to bring up a potential addition to the bullet-point to-do items in this task. Is it worth adding an item to ensure backwards compatibility with SASS file lookup during compilation? 

For example, if you were to test the current blueprint using the following `ember new my-app -b ember-module-unification-blueprint` and then added ember-paper it would give you the following error: 
```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File to import not found or unreadable: ember-paper.
```

I'm assuming this is simply because the broccoli tree of the output of the ember-paper addon is incompatible with the new lookup rules, but I just don't notice a bullet point that covers this eventuality (I could be wrong).

**Comment by mixonic** [comment]
Closed in favor of https://github.com/emberjs/ember.js/issues/16373
