### ISSUE TITLE
[Quest] Implement optional-jQuery RFC

### ISSUE THREAD

**Issue by simonihmig** [ember-cli/ember-cli#7842]
This is to track the implementation of [RFC294](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#introduce-emberjquery-package). As it covers a few different repos, the issue here will track the status in a single place.

## Work items

* `ember-source`
  - [x] Make Ember go into no-jQuery mode based on the flag instead of looking at `global.jQuery` (see https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/jquery.js)
(PR: https://github.com/emberjs/ember.js/pull/16687)
  - [x] add a deprecation warning when accessing `jQuery.Event` specific properties, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#introducing-ember-jquery-legacy-and-deprecating-jqueryevent-usage)
(PR: emberjs/ember.js#16690)
* [`@ember/optional-features`](https://github.com/emberjs/ember-optional-features)
  - [x] Add `jquery-integration` flag 
(Issue: https://github.com/emberjs/ember-optional-features/issues/3, PR: https://github.com/emberjs/ember-optional-features/pull/17)
* [`@ember/jquery`](https://github.com/emberjs/ember-jquery)
  - [x] import jQuery if the integration flag is not disabled, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#introduce-emberjquery-package)
* ember-cli
  - [x] stop importing jQuery (`vendorFiles`) when `@ember/jquery` is present, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#introduce-emberjquery-package) (@cibernox https://github.com/ember-cli/ember-cli/pull/7841)
  - [x] stop importing jQuery (`vendorFiles`) when the integration flag is false, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#add-an-opt-out-flag)
  - [x] add a warning/deprecation message when `@ember/jquery` is not installed and the integration flag is either not specified or is set to true, suggesting to install it
  - [x] add `@ember/jquery` to the default app blueprint 
(PR: https://github.com/ember-cli/ember-cli/pull/7844)
* `ember-jquery-legacy`
  - [x] create repo 
  - [x] implement `normalizeEvent()`, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#introducing-ember-jquery-legacy-and-deprecating-jqueryevent-usage)
(PR: https://github.com/emberjs/ember-jquery-legacy/pull/1)
* website
  - [x] add an opt-out guide 
(PR: https://github.com/ember-learn/guides-source/pull/64)
  - [x] add a deprecation guide for `jQuery.Event`, as specified [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#deprecation-guide)
(PR: https://github.com/ember-learn/deprecation-app/pull/127)
* ember-try
  - [x] provide a mechanism to test addons without jQuery based on the integration flag, see [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#ember-try) (PR: https://github.com/ember-cli/ember-cli/pull/7844)
* emberobserver.com
  - [ ] indicate addon's jQuery dependency, see [here](https://github.com/emberjs/rfcs/blob/master/text/0294-optional-jquery.md#emberobservercom) 

## Collaboration

If someone wants to start work on a specific item, please post this here so I can update the list. More ephemeral style discussions can take place in the `#dev-jquery-removal` Slack channel.

**Comment by cibernox** [comment]
@simonihmig First checkbox can be checked. Checkbox in `@ember/jquery` ca also be checked. All checkboxes under `ember-cli` can be checked.

**Comment by simonihmig** [comment]
@cibernox nice work! 🎉

> All checkboxes under ember-cli can be checked.

Checked the first three. This is AFAICT not yet implemented though: `add @ember/jquery to the default app blueprint`

> Checkbox in @ember/jquery ca also be checked

See https://github.com/emberjs/ember-jquery/issues/3

**Comment by simonihmig** [comment]
I can try to work on the `jQuery.Event` handling over the weekend, i.e. the deprecation message and the `ember-jquery-legacy` addon. If nobody else is eager to take this at least... :)

@rwjblue can you please create the repo for that?

**Comment by rwjblue** [comment]
I submitted https://github.com/ember-cli/ember-cli/pull/7844 to address this point:

> add `@ember/jquery` to the default app blueprint

**Comment by rwjblue** [comment]
>  @rwjblue can you please create the repo for that?

Done: https://github.com/emberjs/ember-jquery-legacy

**Comment by simonihmig** [comment]
To be reviewed:
https://github.com/emberjs/ember.js/pull/16690
https://github.com/emberjs/ember-jquery-legacy/pull/1

**Comment by simonihmig** [comment]
Two more:
* https://github.com/ember-learn/deprecation-app/pull/127
* https://github.com/emberjs/ember.js/pull/16693

**Comment by simonihmig** [comment]
Fyi, just updated the Readme's of https://github.com/emberjs/ember-jquery and https://github.com/emberjs/ember-jquery-legacy. Feel free to improve if necessary, but for now better than nothing!

Looking at the above To Do list, except for the guides and emberobserver.com issues left over, this RFC has basically just been implemented! 🎉

Thanks @rwjblue and @cibernox, that was fun! 😀

**Comment by cibernox** [comment]
@kategengler How much work do you think it will be to surface wether or not an addon requires jquery?

We can know it by checking of the addon has a `config/optional-features.json` containing `"jquery-integration": false`.

**Comment by kategengler** [comment]
@cibernox My plan was to use the results of ember-try runs to get the jQuery status, using the ability added here https://github.com/emberjs/ember-optional-features/issues/2

**Comment by cibernox** [comment]
@kategengler so you want to check that at least one scenario runs without jQuery from the build artifacts of every run?

**Comment by kategengler** [comment]
@cibernox EmberObserver runs the an ember-try config against addons, and has the results (displays for top 100). So, as long as I have a config that can test jQuery on/off, I can get results for each addon (that has an available repo). I need is the try config (not sure what that looks like yet) + any other requirements (minimum CLI version maybe?).

We should also probably have the default ember-try config contain scenarios with and without jQuery. (@rwjblue thoughts?)

**Comment by simonihmig** [comment]
> We should also probably have the default ember-try config contain scenarios with and without jQuery. 

@kategengler Robert did that just recently in https://github.com/ember-cli/ember-cli/pull/7844!

I guess the idea would be to look at `config/optional-features.json` for the `jquery-integration` flag?
https://github.com/ember-cli/ember-cli/pull/7844/files#diff-d2dc84345b41f0668236a56410bcc7bcR2
