### ISSUE TITLE
Remove implicit CSS minification

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/ember-cli#8457]
In the current state (v3.7.x) Ember CLI automatically minifies CSS files using [`clean-css`](https://github.com/jakubpawlowicz/clean-css) when building for the `production` environment. 

For this to work Ember CLI has a direct dependency on https://github.com/ember-cli/ember-cli-preprocess-registry/ v3.x, which falls back to `broccoli-clean-css` when no other `minify-css` preprocessor is found in the registry. One example of such a preprocessor is https://github.com/ember-cli/ember-cli-clean-css.

The goal of this issue is to remove the fallback and make CSS minification an explicit thing, similar to what we do with `ember-cli-uglify` for JS code.

### Todo

- [ ] add https://github.com/ember-cli/ember-cli-clean-css to several test apps and check if the minified CSS output is the same (or possibly better)
- [ ] if needed, port https://github.com/ember-cli/ember-cli-preprocess-registry/pull/54 to `ember-cli-clean-css` (/cc @Emrvb)
- [ ] add `ember-cli-clean-css` as a dependency to the `app` and `addon` blueprints
- [ ] (after ☝️!) update `ember-cli-preprocess-registry` to a version without the `clean-css` fallback

### Related

- https://github.com/ember-cli/ember-cli/issues/8359

**Comment by RichardOtvos** [comment]
@t-sauer Can I take this? This would be my first issue in ember-cli, but would be happy to help

**Comment by t-sauer** [comment]
@RichardOtvos I think you mentioned the wrong person 😄

**Comment by RichardOtvos** [comment]
sorry @t-sauer ! 😬 
@Turbo87 can I take this? If it helps I'm a lot better at coding than mentioning people in github issue comments 😁

**Comment by chendraayan** [comment]
Is there any workaround for this, until this enhancement is released?

**Comment by void-mAlex** [comment]
let me have a go at this :)

**Comment by void-mAlex** [comment]
so finally got around to spending some time on this and ran into some issues
what I've done so far was the prep work to ensure the output is the same
I've gone through most of the repos on the ember-learn and ember-guides orgs cloned them and did two builds; one as is and one after I've added https://github.com/ember-cli/ember-cli-clean-css
for the most part what I've observed is that the addon does a bit more in terms of optimizing the css classes removing redundant ones and adding the leftover properties as standalone if needed (not sure if that's intended or not)

but the worrying part is that it does not handle the relative `url()` function well at all and here is an example

_all examples are from SuperRentals repo [https://github.com/ember-learn/super-rentals](url)_

```css
.tomster {
  background: url(../assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png) no-repeat;
  background-size: contain;
  height: 200px;
  width: 200px;
  top: -25px
}
```
becomes
```css
.tomster {
  background: url(../../../../tmp/broccoli-1189SeGOWMQ9D4Gu/out-201-funnel/assets/images/teaching-tomster-756a14cc8225582bf530b5d0c624db4d.png);
  background-size: contain;
  background-repeat: no-repeat;
  height: 200px;
  width: 200px;
  position: relative;
  top: -25px
}
```
for absolute urls (at least on the builds on my machine it's behaving)

another big difference is that it's not removing duplicate property declarations
unprocessed file:
```css
/**
 * Top Navigation
 */

.menu {
  height: 4em;
  background-color: #677ae4;
  background-color: #05526A;
  background-color: #e46855;
}
```
original css output
```css

.menu {
  height: 4em;
  background-color: #e46855
}
```
addon css output
```css
.menu {
  height: 4em;
  background-color: #677ae4;
  background-color: #05526a;
  background-color: #e46855
}
```
which this won't hurt the final appearance of the app it does mean that it might ever so slightly increase the css size

just to confirm I've done these tests on the master branch of the addon as the published version is using babel version 5 and throws additional errors at build time.

@locks @rwjblue I'll try to look at why the addon is not handling relative urls, but any guidance would be much appreciated, I do believe that is a showstopper  for this ticket going forward

**Comment by rwjblue** [comment]
> the addon does a bit more in terms of optimizing the css classes removing redundant ones and adding the leftover properties as standalone if needed (not sure if that's intended or not)

I suspect this is due to the changes in clean-css itself (since we are bumping to a new major version).

> but the worrying part is that it does not handle the relative url() function well at all and here is an example

Ya, this is definitely an issue we have to address. Would you mind making a new issue over in the ember-cli-clean-css addon so we can try to figure out what is going on there?

> another big difference is that it's not removing duplicate property declarations unprocessed file:

My guess is that this is related to changes in clean-css, and likely there is a configuration option we can use to modify.

> just to confirm I've done these tests on the master branch of the addon as the published version is using babel version 5 and throws additional errors at build time.

If you have the time, a spruce up of ember-cli-clean-css addon would be welcome. I'm happy to release a breaking change (drop Node < 10, update babel, etc) as needed. I mostly just need someone with time/energy to help push forward with testing / integrating.

Thanks for digging in here!

**Comment by void-mAlex** [comment]
one concern with adding the new addon to the blueprints is how it could interact with users of sass or less, is that covered anywhere? should I add it to the list of things that need to be checked?

**Comment by rwjblue** [comment]
> one concern with adding the new addon to the blueprints is how it could interact with users of sass or less

I don't think it would change behaviors for them (any different from an app that doesn't use a preprocessor), but it seems good to add that to a list of things to check...

**Comment by mansona** [comment]
Maybe https://github.com/ember-learn/ember-website/pull/849 satisfies the first checkpoint in the todo list? 😂  it definitely makes the situation better because it fixes a bug from over-minification 🙈

**Comment by nickschot** [comment]
To add to that, the file size won't be smaller as we minify less aggressively by default (which fixes the original issues). Gzip seems to take away most of the remaining duplication though.

**Comment by kategengler** [comment]
Closing as we merged https://github.com/ember-cli/ember-cli/pull/10244 to update ember-cli-preprocess-registry and pull out the behavior to ember-cli-clean-css
