### ISSUE TITLE
Update testing dependencies (ember-qunit, @ember/test-helpers, qunit, qunit-dom)

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli#9335]
A major version release of the testing libraries is afoot! The goals of the next iteration are:

* Drop support for older unsupported Node versions
* Be more Embroider compatible
* Do less "weird stuff"
* Give versioning control back to applications (aka "do less bad magic")

Concretely, those goals result to the following major changes in `ember-qunit@5` :

* Drop support for older Node versions
* Remove usage of APIs that are not Embroider compatible
  * `{{content-for` usage has been replaced by having the `tests/index.html` directly include our expected DOM content
  * `app.import` has been removed in favor of leveraging imports along with ember-auto-import / Embroider to process them
* Move `qunit` and `@ember/test-helpers` into project `devDependencies` (`ember-qunit` is moving them to be `peerDependencies` along with some helpful validations and error messages to help guide folks down the path)

---

Roll out work:

- [x] Land and release https://github.com/simplabs/qunit-dom/pull/816
- [x] Release Embroider with the fixes from https://github.com/embroider-build/embroider/pull/531
- [ ] Release prerelease / beta versions
  - [x] `@ember/test-helpers`
  - [x] `ember-qunit`
  - [x] `qunit-dom`
- [x] Update blueprint https://github.com/ember-cli/ember-cli/pull/9340
  - [x] Update app blueprint to include the `tests/index.html` snippet 
  - [x] Update app blueprint to add `qunit` and `@ember/test-helpers` to `devDependencies` 
  - [x] Update `qunit-dom` in the app blueprint
- [ ] Release final/stable versions
  - [x] `@ember/test-helpers` (https://github.com/emberjs/ember-test-helpers/releases/tag/v2.0.0)
  - [ ] `ember-qunit`
  - [ ] `qunit-dom`
- [ ] Update blueprint to use final/stable versions

**Comment by scalvert** [comment]
What can I do to help?

**Comment by rwjblue** [comment]
FYI - This landed in ember-cli@3.23.0-beta.1.

**Comment by bertdeblock** [comment]
Anything left to be done or can we close this issue?

**Comment by rwjblue** [comment]
Thanks @bertdeblock!
